name: 6-Hour Node Update

on:
  schedule:
    # 对应北京时间：08:00, 12:00, 16:00, 20:00, 00:00
    - cron: '0 0,4,8,12,16 * * *'
  workflow_dispatch: # 保持手动触发，方便测试

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Run Script
        run: |
          pip install requests
          python main.py

      - name: Push Changes
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add subscribe.txt
          git commit -m "Update nodes: $(date)" || exit 0
          git push
